language: node_js
node_js:
    - "8"
after_success:
    - npm run coverage
deploy:
    provider: npm
    api_key: "72c8a1db-6150-4b3b-8a95-13588c6f87f6"
    skip_cleanup: true
    on:
        branch: master
        tags: true
