language: node_js
node_js:
- '8'
after_success:
- npm run coverage
deploy:
  provider: npm
  api_key:
    secure: pCRgY92sPc+rNpfZ6uZT6eF6LkRnSKUjJ1XZvewRlahY7mZk/RQqFfi28woFVepxIA959v4d1ua39eGJUGczzXlbqzOCe5LD53/nVDygjKXk/P8rvPurwxbgMmEZVtuAsOHP7vQDcAMa9DsCq/yYwiF78fr82ZvxqQdZC2VrkJVe3wl5qeKpHkaIW+6SntvjsrBN6S6hiKxTt/LOQ3TFF4xOdpaGX+4UfPRU70nO8e8NyvAAabHNuekowJK8O5ERbwBIlVGJL81Bp846/I592Qaxc3pESyfMkIAj/qSSla60HBNu+8dC68HrzejaY24A1Lgz/7JvaM0yY4xNo3b/0MSEhJ5CCrqHtMJM+UQtgmyNGLxx2HV8P95OqYSfJIQp9suL+e4MdVFm+Ee2qVAfTncZiB89AaZq3AankrjNVsYHxWG4vWJ6g9t1u8gMJfeVRvCfAv46lSnyuVgAMJLzfudCJ4FDpGohbcbX0QMUZhvXipluj2+foPk90fmP9/TB5yZbKCUE/lUQOAFkTgBkfU8E+CMuoekB7C6AN3viZ9zpDlPGicBKHFFT0IkhtT22egz0iC5uMIw45nddjab6gyuXHlPLW4XoaNST6GxIc0REh3MW3N87CU3wdqqLIqauldgmlQ+PoMpYU0Yhle7TXWmuljS65l0fs/DNHCE+Dog=
  skip_cleanup: true
  on:
    branch: master
